name: proxyServer
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: wwts <im@wwts.me>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.9
  dio: ^3.0.7
  shelf_router: ^0.7.4

dev_dependencies:
  pedantic: ^1.8.0
